### ISSUE TITLE
OSX Needs command line tools installed

### ISSUE THREAD

**Issue by tillschumann** [pramodskumbhar/spack-packages#38]
```
bluebrain243:~ schumann$ ls /Library/Developer/CommandLineTools/usr/share/man/whatis 
bluebrain243:~ schumann$ xcode-select -p
/Applications/Xcode.app/Contents/Developer
bluebrain243:~ schumann$ xcode-select --install
xcode-select: note: install requested for command line developer tools
```

**Comment by pramodskumbhar** [comment]
Also add instructions about below error when directory is deleted : 
```
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
Traceback (most recent call last):
  File "/gpfs/bbp.cscs.ch/home/kumbhar/workarena/systems/lugviz/softwares/sources/spack/bin/spack", line 81, in <module>
    sys.exit(spack.main.main())
  File "/gpfs/bbp.cscs.ch/home/kumbhar/workarena/systems/lugviz/softwares/sources/spack/lib/spack/spack/main.py", line 552, in main
    return _main(command, parser, args, unknown)
  File "/gpfs/bbp.cscs.ch/home/kumbhar/workarena/systems/lugviz/softwares/sources/spack/lib/spack/spack/main.py", line 435, in _main
    set_working_dir()
  File "/gpfs/bbp.cscs.ch/home/kumbhar/workarena/systems/lugviz/softwares/sources/spack/lib/spack/spack/main.py", line 96, in set_working_dir
    os.chdir(spack_prefix)
NameError: global name 'spack_prefix' is not defined
```
